image: gitpod/workspace-mongodb

tasks:
  - name: Setup and seed
    init: |
      cd server
      npm install
      cd ../admin-gitpod
      npm install
      cd ../openapi
      npm install
      cd ../server
      node seed-db-gitpod.js

    command: |
      region=$(echo ${GITPOD_WORKSPACE_URL} | cut -d'.' -f2)
      echo "VITE_REACT_APP_SERVER_URL=https://8080-${GITPOD_WORKSPACE_ID}.${region}.gitpod.io" > /workspace/api-documentation-course-gitpod/admin-gitpod/.env

  - name: Run Node.js server
    command: |
      cd server
      node index-gitpod.js

  - name: React admin panel
    command: |
      cd admin-gitpod
      npm run dev

  - name: OpenAPI setup
    command: |
      cd openapi
      if [ ! -f openapi.yml ]; then
        echo "openapi.yml does not exist. Creating a copy from openapi.original.yml..."
        cp openapi.original.yml openapi.yml || { echo "Failed to copy openapi.original.yml"; exit 1; }
        node wipeOpenApiDescription.js
      else
        echo "openapi.yml already exists. Exiting script."
        exit 0
      fi

ports:
  - name: Node.js server
    port: 8080
    onOpen: ignore
    visibility: public

  - name: React admin panel
    port: 5173
    onOpen: open-browser
    visibility: public
